variable "aws_region" {}
variable "vpc_cider" {}
variable "public_subnets_cider" {}
variable "private_subnets_cider" {}
variable "AZS-Public" {}
variable "AZS-Private" {}
variable "tgn-vpc" {}
variable "env" {}
variable "tgn-vpc-igw" {}
variable "tgn-public-RT" {}
variable "tgn-private-RT" {}
variable "cider" {}
variable "instance-public-ip" {}
variable "instance-test1" {}